apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
    app.kubernetes.io/component: mongo
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/name: mongo
    app.kubernetes.io/part-of: mongo-app
    app.openshift.io/runtime: mongodb
    app.openshift.io/runtime-namespace: test-app
  name: mongo
  namespace: baseball-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongo
        deployment: mongo
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/test-app/mongo@sha256:e6270eb2e6cd23adb333b559747e0e4843ae81944bd1e2236f5fca64260061a9
        imagePullPolicy: IfNotPresent
        name: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - mountPath: /data/configdb
          name: mongo-1
        - mountPath: /data/db
          name: mongo-2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      livenessProbe:
        httpGet:
          path: /
          port: 27017
          scheme: HTTP
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: mongo-1
      - emptyDir: {}
        name: mongo-2