apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: baseball-app
  labels:
    app: baseball-app
    app.kubernetes.io/part-of: baseball-app
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
