apiVersion: v1
kind: Service
metadata:
  name: baseball-backend-service
  namespace: baseball-app
spec:
  selector:
    app: baseball-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
