kind: Deployment
apiVersion: apps/v1
metadata:
  name: baseball-frontend
  namespace: baseball-app
  labels:
    app: baseball-app
    app.kubernetes.io/part-of: baseball-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baseball-frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: baseball-frontend
    spec:
      containers:
        - name: container
          image: 'daveross0/baseball-helper:1.3'
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: IfNotPresent
          env: []
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
