apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "Baseball Inning Alignment Tool"
    openshift.io/display-name: baseball-app
  labels:
    kubernetes.io/metadata.name: baseball-app
  name: baseball-app